import "./lua/print"
import "./lua/custom"
import "./ao/ao-id"
import "./ao/send"

import "./table/table"
import "./table/key-value"
import "./table/create"
import "./table/get"
import "./table/insert"
import "./table/length"
import "./table/set"